final Map<String, String> ar = {

  // "Groups" : "Groups",
  // "Students" : "Students",
  // "Profile" : "Profile",
  //
  // "report_parent_title" : "تقرير خاص بمتابعة ولي الأمر",
  // "infoText" : "نحيط سيادتكم علما أن الطالب",
  // "hasAttended" : "قدر حضر حصة اليوم",
  // "hasNotAttended" : "لم يحضر حصة اليوم",
  // "withDate" : "بتاريخ",
  // "His behavior during the session was" : "وكان سلوكه أثناء الحصة",
  // "The test score for the above was" : "ودرجة الاختبار على ما سبق",
  //
  //

  "Home": "الرئيسية",
  "Groups": "المجموعات",
  "Students": "الطلاب",
  "Settings": "الإعدادات",

  "Session Name:": "اسم الحصة:",
  "Group:": "المجموعة:",
  "Student Details": "تفاصيل الطالب",
  "View all sessions": "عرض جميع الجلسات",
  "Parent Phone": "هاتف ولي الأمر",
  "Student Phone": "هاتف الطالب",
  "Grade Name": "الصف الدراسي",
  "No Group": "لا يوجد مجموعة",
  "Day": "اليوم",
  "Are you sure to delete ?": "هل أنت متأكد من الحذف؟",
  "Add to Group": "إضافة إلى المجموعة",
  "Group Name is required": "اسم المجموعة مطلوب",
  "Grade": "الصف",
  "Grade is required": "الصف مطلوب",
  "Select Day": "اختر اليوم",
  "Save": "حفظ",
  "For Contact": "للتواصل",
  "Got It": "حسناً",
  "Do you want to contact now?": "هل تريد التواصل الآن؟",
  "Share via": "مشاركة عبر",
  "WhatsApp": "واتساب",
  "WhatsApp Business": "واتساب للأعمال",
  "Other": "أخرى",
  "Don't ask me again": "لا تسأل مرة أخرى",
  "Select Student to": "اختر طالبًا",
  "Group Details": "تفاصيل المجموعة",
  "Group Info": "معلومات المجموعة",
  "No students found": "لا يوجد طلاب",
  "No Active Sessions": "لا توجد جلسات نشطة",
  "View All Sessions": "عرض جميع الجلسات",
  "Edit Group": "تعديل المجموعة",
  "Group not found": "لم يتم العثور على المجموعة",
  "Group edited successfully": "تم تعديل المجموعة بنجاح",
  "No Groups Found": "لا توجد مجموعات",
  "Running Session": "الحصة قيد التشغيل",
  "No Running Sessions Found": "لا توجد جلسات قيد التشغيل",
  "Today Groups": "مجموعات اليوم",
  "User Name": "اسم المستخدم",
  "Password": "كلمة المرور",
  "Login": "تسجيل الدخول",
  "Student Report": "تقرير الطالب",
  "View": "عرض",
  "Send": "إرسال",
  "Notes": "ملاحظات",
  "No Notes": "لا توجد ملاحظات",
  "No note": "لا توجد ملاحظة",
  "Session": "الحصة",
  "Session Details": "تفاصيل الحصة",
  "Session Not Found": "لم يتم العثور على الحصة",
  "Invalid Args": "بيانات غير صالحة",
  "Attended": "حاضر",
  "Behavior": "السلوك",
  "Homework": "الواجب المنزلي",
  "Send Report": "إرسال التقرير",
  "Sessions": "الجلسات",
  "Student Name": "اسم الطالب",
  "Student Name is required": "اسم الطالب مطلوب",
  "Parent Phone is required": "هاتف ولي الأمر مطلوب",
  "Phone": "الهاتف",
  "Edit Student": "تعديل الطالب",
  "Student not found": "لم يتم العثور على الطالب",
  "Ok": "موافق",
  "ok_well": "حسنًا",
  "yes": "نعم",
  "Cancel": "إلغاء",
  "Retry": "إعادة المحاولة",
  "Status": "الحالة",
  "End Session": "إنهاء الحصة",
  "Quiz": "اختبار",
  "Quiz:": "الاختبار:",
  "Start Date:": "تاريخ البدء:",
  "Session Status": "حالة الحصة",
  "Start session": "بدء الحصة",
  "Quiz Grade if found": "درجة الاختبار إن وجدت",
  "Session Name (Optional)": "اسم الحصة (اختياري)",
  "Start": "بدء",
  "please enter valid quiz grade": "الرجاء إدخال درجة اختبار صالحة",
  "Update Student Activity": "تحديث نشاط الطالب",
  "Sunday": "الأحد",
  "Monday": "الاثنين",
  "Tuesday": "الثلاثاء",
  "Wednesday": "الأربعاء",
  "Thursday": "الخميس",
  "Friday": "الجمعة",
  "Saturday": "السبت",
  "Fully Done": "كامل",
  "Incompleted": "غير مكتمل",
  "Not Done": "متروك",
  "Active": "نشط",
  "Inactive": "غير نشط",
  "Acceptable": "مقبول",
  "Poor": "مشاغب",
  "Good": "جيد",
  "Create New Groups": "إنشاء مجموعات جديدة",
  "No Today Groups": "لا توجد مجموعات اليوم",
  "View Details": "عرض التفاصيل",
  "Attendance:": "الحضور:",
  "Attendance": "الحضور",
  "Behavior:": "السلوك:",
  "Homework:": "الواجب المنزلي:",
  "Quiz Grade:": "درجة الاختبار:",
  "Quiz Grade": "درجة الاختبار",

  "report_parent_title": "تقرير متابعة ولي الأمر",
  "infoText": "نحيط سيادتكم علما أن الطالب",
  "fulReportInfoText": "نحيط سيادتكم تقرير شامل للطالب",

  "attended the class on": "قدر حضر حصة اليوم",
  "attended": "قد حضر",
  "Session Day": "حصة اليوم",
  "didn't attend the class on": "لم يحضر اليوم",
  "didn't attend": "لم يحضر",
  "withDate": "في تاريخ",
  "The student's behavior during the class was": "وكان سلوكه أثناء الحصة",
  "The status of the previous homework was": "وكان واجب الحصة الماضية",
  "Language": "اللغة",
  "English": "انجليزي",
  "Arabic": "عربي",
  "Group Name": "الاسم",
  "The student got": "ودرجة الاختبار على ما سبق:",
  "marks on the quiz": "",
  "Are you sure to call": "هل أنت متأكد من الاتصال بـ %s ؟",
  "Create Group": "إنشاء مجموعة",
  "Selected Students": "الطلاب",
  "No Students Selected": "لم يتم تحديد أي طلاب",
  "Select Time From": "حدد الوقت من",
  "Select Time To": "حدد الوقت إلي",
  "Please select grade first": "الرجاء تحديد الصف أولا",
  "No students found without groups": "لم يتم العثور على طلاب بدون مجموعات",
  "Add Student": "إضافة طالب",
  "Homework Notes": "ملاحظات علي الواجب",
  "Behavior Notes": "ملاحظات علي السلوك",
  "Group Time:": "وقت المجموعة:",
  "Date:": "التاريخ:",
  "Update" : "تحديث",
  "Student Info" : "معلومات الطالب",
  "User not active" : "المستخدم غير نشط، يرجى الاتصال بمالك الخدمة",
  "force_update_message" : "تتوفر نسخة أحدث من هذا التطبيق.\n لمواصلة استخدام التطبيق، يرجى التحديث إلى الإصدار الأحدث من المتجر.",
  "Privacy Policy" : "سياسة الخصوصية",
  "Delete Account" : "حذف الحساب",
  "delete_account_confirm_message" : "هل أنت متأكد من حذف حسابك؟",
  "Are you sure to logout" : "هل أنت متأكد من تسجيل خروج؟",
  "Enter Grade" : "أدخل الدرجة",
  "Group has no students" : "لا يوجد طلبة في المجموعة",
  "Under the supervision of" : "تحت إشراف أ/",
  "Hey, Mr." : "أهلاً أ/",
  "Search" : "بحث",
  "All Students" : "كل الطلبة",
  "Sort" : "ترتيب",
  "By group" : "حسب المجموعة",
  "By grade" : "حسب الصف",
  "Reset" : "إعادة تعيين",
  "Without group" : "بدون مجموعة",
  "By Day" : "حسب اليوم",
  "Add student to session" : "إضافة طالب إلى الجلسة",
  "Are you sure you want to delete the session" : "هل أنت متأكد أنك تريد حذف الجلسة؟",
"Are you sure you want to add students to this session?" : "هل أنت متأكد أنك تريد إضافة الطالب إلى هذه الجلسة؟",
  "Are you sure you want to delete this report?" : "هل أنت متأكد أنك تريد حذف هذا التقرير؟",
  "Not Determined" : "لم يُحدد",
  "Total Attendance" : "إجمالي الحضور",
  "Average Grade" : "متوسط الدرجات",
  "Date" : "التاريخ",
  "No Reports Found" : "لم يتم العثور على أي تقارير",
"View Full Report" : "عرض تقرير شامل",
  "Full Report" : "تقرير شامل",
  "subscription_message" : "اشتراكك غير فعال، يرجى التواصل مع مالك الخدمة.",
  "No": "لا",
  "Yes": "نعم",
  "Renew": "تجديد",
  "Close": "إغلاق",
  "Share": "مشاركة",
  "Could not share file": "لا يمكن مشاركة الملف",
  "no_internet_connection" : "لا يوجد اتصال بالإنترنت",
  "subscription_expiring_today_message": "اشتراكك ينتهي اليوم! جدد الآن لتجنب انقطاع الخدمة",
  "subscription_expiring_message": "اشتراكك ينتهي خلال {days} أيام. جدد الآن لتجنب انقطاع الخدمة"





};

/*
* خلي التقرير له عنوان في المنتصف

    [تقرير خاص بمتابعة ولي الأمر]

نحيط سيادتكم علما أن الطالب/...... قدر حضر حصة اليوم/... بتاريخ/....

وكان سلوكه أثناء الحصة:
جيد / مقبول / مشاغب

وكان واجب الحصة الماضية:
كامل / ينقصه عدد (...) صفحة /متروك

ودرجة الاختبار على ما سبق:
(.../ ...) وضح بجانبها المجموع الكلي*/
