import 'dart:io';

/// Code generation script to extract localization keys from translationsMap
/// and generate a constants class for type-safe key access.
void main() async {
  print('🚀 Generating localization keys...');

  try {
    final appStringsTranslationFile = File('lib/localization/translations_map.dart');

    if (!await appStringsTranslationFile.exists()) {
      print('❌ AppStringsTranslation file not found at: ${appStringsTranslationFile.path}');
      exit(1);
    }

    final content = await appStringsTranslationFile.readAsString();
    final stringsTranslationKeys = await extractKeysFromStringsEntries(content);

    final allKeys = stringsTranslationKeys.toSet().toList()..sort();

    if (allKeys.isEmpty) {
      print('⚠️  No localization keys found in translations_map.dart');
      return;
    }

    print('📊 Total unique keys: ${allKeys.length}');

    final generatedCode = generateAppStringsKeysClass(allKeys);

    // Write to generated file
    final outputFile = File('lib/localization/generated/app_strings_keys.dart');
    await outputFile.parent.create(recursive: true);
    await outputFile.writeAsString(generatedCode);

    print('✅ Generated ${allKeys.length} keys in: ${outputFile.path}');
    print('📦 Keys generated: ${allKeys.join(', ')}');

  } catch (e) {
    print('❌ Error generating keys: $e');
    exit(1);
  }
}

/// Extracts localization keys from translationsMap in translations_map.dart
Future<List<String>> extractKeysFromStringsEntries(String content) async {
  final keys = <String>[];

  // Find the translationsMap Map content
  final translationsMapRegex = RegExp(
    r'final\s+Map<String,\s*TranslationModel>\s+translationsMap\s*=\s*\{(.*?)\};',
    multiLine: true,
    dotAll: true,
  );

  final match = translationsMapRegex.firstMatch(content);
  if (match == null) {
    print('❌ Could not find translationsMap');
    return keys;
  }

  final entriesContent = match.group(1)!;
  print('📋 Found translationsMap content');

  // Extract key-value pairs: "key": TranslationModel(...)
  final keyRegex = RegExp(
    r'"([^"]+)"\s*:\s*TranslationModel\(',
    multiLine: true,
  );

  for (final m in keyRegex.allMatches(entriesContent)) {
    final key = m.group(1)!;
    keys.add(key);
    print('🔑 Found key: $key');
  }

  return keys..sort();
}

/// No longer used — ar map is derived from translationsMap in translations_map.dart.
Future<List<String>> extractKeysFromArMap(File appTranslationFile) async {
  return [];
}

/// Generates the AppStringsKeys constants class
String generateAppStringsKeysClass(List<String> keys) {
  final buffer = StringBuffer();

  // File header
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by tools/generate_keys.dart');
  buffer.writeln('// Run: dart run tools/generate_keys.dart');
  buffer.writeln('');
  buffer.writeln('/// Auto-generated localization keys constants.');
  buffer.writeln('/// Provides type-safe access to localization keys.');
  buffer.writeln('class AppStringsKeys {');
  buffer.writeln('  AppStringsKeys._();');
  buffer.writeln('');

  // Generate constants — track used names to avoid duplicate_definition errors
  final usedNames = <String, int>{};
  for (final key in keys) {
    String constantName = _toCamelCase(key);
    if (usedNames.containsKey(constantName)) {
      final count = usedNames[constantName]! + 1;
      usedNames[constantName] = count;
      constantName = '$constantName$count';
    } else {
      usedNames[constantName] = 1;
    }
    buffer.writeln('  /// Key: "$key"');
    buffer.writeln('  static const String $constantName = "$key";');
    buffer.writeln('');
  }

  buffer.writeln('}');

  return buffer.toString();
}

/// Converts snake_case, kebab-case, or space-separated strings to camelCase
String _toCamelCase(String input) {
  // If input is already in valid camelCase format, return as-is (after reserved word check)
  if (_isValidCamelCase(input)) {
    // Check if it's a Dart reserved word and prefix if needed
    if (_isDartReservedWord(input)) {
      return 'key${input[0].toUpperCase()}${input.substring(1)}';
    }
    return input;
  }

  // Split by spaces, underscores, hyphens, forward slashes, and other special characters
  final parts = input.split(RegExp(r'[_\s\-\/\\\.,;:!@#$%^&*()+={}\[\]|<>?`~]+'));
  if (parts.isEmpty) return 'unknownKey';

  // Filter out empty parts
  final nonEmptyParts = parts.where((part) => part.isNotEmpty).toList();
  if (nonEmptyParts.isEmpty) return 'unknownKey';

  String result = nonEmptyParts.first.toLowerCase();

  for (int i = 1; i < nonEmptyParts.length; i++) {
    final part = nonEmptyParts[i];
    if (part.isNotEmpty) {
      result += part[0].toUpperCase() + part.substring(1).toLowerCase();
    }
  }

  // Check if result is a Dart reserved word and prefix if needed
  if (_isDartReservedWord(result)) {
    result = 'key${result[0].toUpperCase()}${result.substring(1)}';
  }

  // Ensure the result is a valid Dart identifier
  if (result.isEmpty || !RegExp(r'^[a-zA-Z_][a-zA-Z0-9_]*$').hasMatch(result)) {
    return 'key${result.hashCode.abs()}'; // Fallback to hash-based name
  }

  return result;
}

/// Checks if a string is already in valid camelCase format
bool _isValidCamelCase(String input) {
  // Must start with lowercase letter or underscore
  // Can contain letters, numbers, but no special characters or spaces
  // Should not contain underscores, spaces, or other separators (pure camelCase)
  return RegExp(r'^[a-z_][a-zA-Z0-9]*$').hasMatch(input) &&
         !input.contains('_') &&
         !input.contains(' ') &&
         !input.contains('-');
}

/// Checks if a string is a Dart reserved word
bool _isDartReservedWord(String word) {
  const dartReservedWords = {
    'abstract', 'as', 'assert', 'async', 'await', 'break', 'case', 'catch',
    'class', 'const', 'continue', 'covariant', 'default', 'deferred', 'do',
    'dynamic', 'else', 'enum', 'export', 'extends', 'extension', 'external',
    'factory', 'false', 'final', 'finally', 'for', 'function', 'get', 'hide',
    'if', 'implements', 'import', 'in', 'interface', 'is', 'late', 'library',
    'mixin', 'new', 'null', 'on', 'operator', 'part', 'required', 'rethrow',
    'return', 'set', 'show', 'static', 'super', 'switch', 'sync', 'this',
    'throw', 'true', 'try', 'typedef', 'var', 'void', 'while', 'with', 'yield',
    // Common types that might cause conflicts
    'String', 'int', 'double', 'bool', 'List', 'Map', 'Set', 'Object', 'Function'
  };

  return dartReservedWords.contains(word);
}